### ISSUE TITLE
Really need to randomize the /var/jb path

### ISSUE THREAD

**Issue by H5GG** [opa334/Fugu15#12]
hi boss, is it possible for us to randomize the /var/jb path?

It is not a good idea to temporarily remove the /var/jb symbolic link, 
it will cause a lot of problems,  https://theapplewiki.com/wiki/Rootless#Dilemmas
and can also be detected:  https://github.com/tuancc-repo/JBDetect15/blob/2424a9ef349374540cabd5f5fdec811eb8614c3f/main.m#L251

If we could randomize the /var/jb path, we'd never have to worry about how acess/stat detects jailbroken files.
 😍

**Comment by opa334** [comment]
NO, please stop spamming
