### ISSUE TITLE
Would it be possible to "backport" this jailbreak to iOS 14.6-14.8.1 for A12-A14 devices?

### ISSUE THREAD

**Issue by bigfloppa234** [opa334/Fugu15#14]

**Comment by Liam0205** [comment]
unc0ver 8.0.2 is for you.

https://unc0ver.dev/

**Comment by egigoka** [comment]
> unc0ver 8.0.2 is for you.
> 
> https://unc0ver.dev/

Uncover on A12-A14 only up to 14.5
