### ISSUE TITLE
Sileo Missing

### ISSUE THREAD

**Issue by rafaelkloster** [opa334/Fugu15#9]
After jailbroken, sileo doesnt appears. Only Zebra.

Im using iphone 13, ios, 15.2. Fugu Beta 4. Installed by TrollStore 1.5.1.

**Comment by Liam0205** [comment]
Rebuild icon cache from TrollStore. If still not work, reboot your device and re-jailbreak.

**Comment by rafaelkloster** [comment]
I’ve done that already. It doesn’t work.

**Comment by Liam0205** [comment]
Check if there is a `Sileo-Nightly.app` folder under the path `/var/jb/Applications`.

**Comment by rafaelkloster** [comment]
> Check if there is a `Sileo-Nightly.app` folder under the path `/var/jb/Applications`.

No, it’s not. What can I do?

**Comment by Liam0205** [comment]
Sileo-Nightly.app should be extracted while Jailbreaking. If this directory does not exist, either the jailbreak has issues or you have installed a non-official version of Fugu15 Max (with modified contents).

For the former, restarting the device and jailbreaking again may resolve the issue. For the latter, please switch to an official test package.

Additionally, Fugu15 Max is currently in its testing phase, so do not expect stability from it.
